<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/transaction.proto

namespace Flow\Entities\Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.Transaction.ProposalKey</code>
 */
class ProposalKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>uint32 key_id = 2;</code>
     */
    protected $key_id = 0;
    /**
     * Generated from protobuf field <code>uint64 sequence_number = 3;</code>
     */
    protected $sequence_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int $key_id
     *     @type int|string $sequence_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 key_id = 2;</code>
     * @return int
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * Generated from protobuf field <code>uint32 key_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkUint32($var);
        $this->key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sequence_number = 3;</code>
     * @return int|string
     */
    public function getSequenceNumber()
    {
        return $this->sequence_number;
    }

    /**
     * Generated from protobuf field <code>uint64 sequence_number = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequenceNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->sequence_number = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProposalKey::class, \Flow\Entities\Transaction_ProposalKey::class);

