<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/account.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.AccountKey</code>
 */
class AccountKey extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>uint32 sign_algo = 3;</code>
     */
    protected $sign_algo = 0;
    /**
     * Generated from protobuf field <code>uint32 hash_algo = 4;</code>
     */
    protected $hash_algo = 0;
    /**
     * Generated from protobuf field <code>uint32 weight = 5;</code>
     */
    protected $weight = 0;
    /**
     * Generated from protobuf field <code>uint32 sequence_number = 6;</code>
     */
    protected $sequence_number = 0;
    /**
     * Generated from protobuf field <code>bool revoked = 7;</code>
     */
    protected $revoked = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $index
     *     @type string $public_key
     *     @type int $sign_algo
     *     @type int $hash_algo
     *     @type int $weight
     *     @type int $sequence_number
     *     @type bool $revoked
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint32 index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>bytes public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sign_algo = 3;</code>
     * @return int
     */
    public function getSignAlgo()
    {
        return $this->sign_algo;
    }

    /**
     * Generated from protobuf field <code>uint32 sign_algo = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSignAlgo($var)
    {
        GPBUtil::checkUint32($var);
        $this->sign_algo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 hash_algo = 4;</code>
     * @return int
     */
    public function getHashAlgo()
    {
        return $this->hash_algo;
    }

    /**
     * Generated from protobuf field <code>uint32 hash_algo = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setHashAlgo($var)
    {
        GPBUtil::checkUint32($var);
        $this->hash_algo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 weight = 5;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>uint32 weight = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 sequence_number = 6;</code>
     * @return int
     */
    public function getSequenceNumber()
    {
        return $this->sequence_number;
    }

    /**
     * Generated from protobuf field <code>uint32 sequence_number = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSequenceNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->sequence_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 7;</code>
     * @return bool
     */
    public function getRevoked()
    {
        return $this->revoked;
    }

    /**
     * Generated from protobuf field <code>bool revoked = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setRevoked($var)
    {
        GPBUtil::checkBool($var);
        $this->revoked = $var;

        return $this;
    }

}

