<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/account.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>uint64 balance = 2;</code>
     */
    protected $balance = 0;
    /**
     * Generated from protobuf field <code>bytes code = 3;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>repeated .flow.entities.AccountKey keys = 4;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>map<string, bytes> contracts = 5;</code>
     */
    private $contracts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type int|string $balance
     *     @type string $code
     *     @type \Flow\Entities\AccountKey[]|\Google\Protobuf\Internal\RepeatedField $keys
     *     @type array|\Google\Protobuf\Internal\MapField $contracts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 balance = 2;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>uint64 balance = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkUint64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes code = 3;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>bytes code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, False);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.AccountKey keys = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.AccountKey keys = 4;</code>
     * @param \Flow\Entities\AccountKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\Entities\AccountKey::class);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> contracts = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getContracts()
    {
        return $this->contracts;
    }

    /**
     * Generated from protobuf field <code>map<string, bytes> contracts = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setContracts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->contracts = $arr;

        return $this;
    }

}

