<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>bytes parent_id = 2;</code>
     */
    protected $parent_id = '';
    /**
     * Generated from protobuf field <code>uint64 height = 3;</code>
     */
    protected $height = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    protected $timestamp = null;
    /**
     * Generated from protobuf field <code>repeated .flow.entities.CollectionGuarantee collection_guarantees = 5;</code>
     */
    private $collection_guarantees;
    /**
     * Generated from protobuf field <code>repeated .flow.entities.BlockSeal block_seals = 6;</code>
     */
    private $block_seals;
    /**
     * Generated from protobuf field <code>repeated bytes signatures = 7;</code>
     */
    private $signatures;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $parent_id
     *     @type int|string $height
     *     @type \Google\Protobuf\Timestamp $timestamp
     *     @type \Flow\Entities\CollectionGuarantee[]|\Google\Protobuf\Internal\RepeatedField $collection_guarantees
     *     @type \Flow\Entities\BlockSeal[]|\Google\Protobuf\Internal\RepeatedField $block_seals
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $signatures
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parent_id = 2;</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>bytes parent_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, False);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 height = 3;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>uint64 height = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkUint64($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimestamp()
    {
        return isset($this->timestamp) ? $this->timestamp : null;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.CollectionGuarantee collection_guarantees = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollectionGuarantees()
    {
        return $this->collection_guarantees;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.CollectionGuarantee collection_guarantees = 5;</code>
     * @param \Flow\Entities\CollectionGuarantee[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollectionGuarantees($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\Entities\CollectionGuarantee::class);
        $this->collection_guarantees = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.BlockSeal block_seals = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBlockSeals()
    {
        return $this->block_seals;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.BlockSeal block_seals = 6;</code>
     * @param \Flow\Entities\BlockSeal[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBlockSeals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\Entities\BlockSeal::class);
        $this->block_seals = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signatures = $arr;

        return $this;
    }

}

