<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/collection.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.Collection</code>
 */
class Collection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated bytes transaction_ids = 2;</code>
     */
    private $transaction_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $transaction_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Collection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes transaction_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactionIds()
    {
        return $this->transaction_ids;
    }

    /**
     * Generated from protobuf field <code>repeated bytes transaction_ids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->transaction_ids = $arr;

        return $this;
    }

}

