<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/collection.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.CollectionGuarantee</code>
 */
class CollectionGuarantee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes collection_id = 1;</code>
     */
    protected $collection_id = '';
    /**
     * Generated from protobuf field <code>repeated bytes signatures = 2;</code>
     */
    private $signatures;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $signatures
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Collection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes collection_id = 1;</code>
     * @return string
     */
    public function getCollectionId()
    {
        return $this->collection_id;
    }

    /**
     * Generated from protobuf field <code>bytes collection_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->collection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Generated from protobuf field <code>repeated bytes signatures = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signatures = $arr;

        return $this;
    }

}

