<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/event.proto

namespace Flow\Entities;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.entities.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>uint32 transaction_index = 3;</code>
     */
    protected $transaction_index = 0;
    /**
     * Generated from protobuf field <code>uint32 event_index = 4;</code>
     */
    protected $event_index = 0;
    /**
     * Generated from protobuf field <code>bytes payload = 5;</code>
     */
    protected $payload = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $transaction_id
     *     @type int $transaction_index
     *     @type int $event_index
     *     @type string $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Entities\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 transaction_index = 3;</code>
     * @return int
     */
    public function getTransactionIndex()
    {
        return $this->transaction_index;
    }

    /**
     * Generated from protobuf field <code>uint32 transaction_index = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTransactionIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->transaction_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 event_index = 4;</code>
     * @return int
     */
    public function getEventIndex()
    {
        return $this->event_index;
    }

    /**
     * Generated from protobuf field <code>uint32 event_index = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEventIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->event_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 5;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

}

