<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/transaction.proto

namespace Flow\Entities;

if (false) {
    /**
     * This class is deprecated. Use Flow\Entities\Transaction\ProposalKey instead.
     * @deprecated
     */
    class Transaction_ProposalKey {}
}
class_exists(Transaction\ProposalKey::class);
@trigger_error('Flow\Entities\Transaction_ProposalKey is deprecated and will be removed in the next major release. Use Flow\Entities\Transaction\ProposalKey instead', E_USER_DEPRECATED);

