<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/transaction.proto

namespace Flow\Entities;

if (false) {
    /**
     * This class is deprecated. Use Flow\Entities\Transaction\Signature instead.
     * @deprecated
     */
    class Transaction_Signature {}
}
class_exists(Transaction\Signature::class);
@trigger_error('Flow\Entities\Transaction_Signature is deprecated and will be removed in the next major release. Use Flow\Entities\Transaction\Signature instead', E_USER_DEPRECATED);

