<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/transaction.proto

namespace Flow\Entities;

use UnexpectedValueException;

/**
 * Protobuf type <code>flow.entities.TransactionStatus</code>
 */
class TransactionStatus
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>PENDING = 1;</code>
     */
    const PENDING = 1;
    /**
     * Generated from protobuf enum <code>FINALIZED = 2;</code>
     */
    const FINALIZED = 2;
    /**
     * Generated from protobuf enum <code>EXECUTED = 3;</code>
     */
    const EXECUTED = 3;
    /**
     * Generated from protobuf enum <code>SEALED = 4;</code>
     */
    const SEALED = 4;
    /**
     * Generated from protobuf enum <code>EXPIRED = 5;</code>
     */
    const EXPIRED = 5;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::PENDING => 'PENDING',
        self::FINALIZED => 'FINALIZED',
        self::EXECUTED => 'EXECUTED',
        self::SEALED => 'SEALED',
        self::EXPIRED => 'EXPIRED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

