<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/execution/execution.proto

namespace Flow\Execution;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.execution.GetTransactionResultRequest</code>
 */
class GetTransactionResultRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes block_id = 1;</code>
     */
    protected $block_id = '';
    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     */
    protected $transaction_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $block_id
     *     @type string $transaction_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Execution\Execution::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes block_id = 1;</code>
     * @return string
     */
    public function getBlockId()
    {
        return $this->block_id;
    }

    /**
     * Generated from protobuf field <code>bytes block_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockId($var)
    {
        GPBUtil::checkString($var, False);
        $this->block_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_id = $var;

        return $this;
    }

}

