<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/execution/execution.proto

namespace Flow\Execution;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.execution.PingResponse</code>
 */
class PingResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Execution\Execution::initOnce();
        parent::__construct($data);
    }

}

