<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/access/access.proto

namespace Flow\Access;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.access.CollectionResponse</code>
 */
class CollectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.flow.entities.Collection collection = 1;</code>
     */
    protected $collection = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Flow\Entities\Collection $collection
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Access\Access::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.flow.entities.Collection collection = 1;</code>
     * @return \Flow\Entities\Collection
     */
    public function getCollection()
    {
        return isset($this->collection) ? $this->collection : null;
    }

    public function hasCollection()
    {
        return isset($this->collection);
    }

    public function clearCollection()
    {
        unset($this->collection);
    }

    /**
     * Generated from protobuf field <code>.flow.entities.Collection collection = 1;</code>
     * @param \Flow\Entities\Collection $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkMessage($var, \Flow\Entities\Collection::class);
        $this->collection = $var;

        return $this;
    }

}

