<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/access/access.proto

namespace Flow\Access;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.access.GetEventsForHeightRangeRequest</code>
 */
class GetEventsForHeightRangeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>uint64 start_height = 2;</code>
     */
    protected $start_height = 0;
    /**
     * Generated from protobuf field <code>uint64 end_height = 3;</code>
     */
    protected $end_height = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type int|string $start_height
     *     @type int|string $end_height
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Access\Access::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 start_height = 2;</code>
     * @return int|string
     */
    public function getStartHeight()
    {
        return $this->start_height;
    }

    /**
     * Generated from protobuf field <code>uint64 start_height = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartHeight($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 end_height = 3;</code>
     * @return int|string
     */
    public function getEndHeight()
    {
        return $this->end_height;
    }

    /**
     * Generated from protobuf field <code>uint64 end_height = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEndHeight($var)
    {
        GPBUtil::checkUint64($var);
        $this->end_height = $var;

        return $this;
    }

}

