<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/access/access.proto

namespace Flow\Access;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>flow.access.TransactionResultResponse</code>
 */
class TransactionResultResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.flow.entities.TransactionStatus status = 1;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>uint32 status_code = 2;</code>
     */
    protected $status_code = 0;
    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>repeated .flow.entities.Event events = 4;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>bytes block_id = 5;</code>
     */
    protected $block_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type int $status_code
     *     @type string $error_message
     *     @type \Flow\Entities\Event[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type string $block_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Flow\Access\Access::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.flow.entities.TransactionStatus status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.flow.entities.TransactionStatus status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Flow\Entities\TransactionStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status_code = 2;</code>
     * @return int
     */
    public function getStatusCode()
    {
        return $this->status_code;
    }

    /**
     * Generated from protobuf field <code>uint32 status_code = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->status_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.Event events = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .flow.entities.Event events = 4;</code>
     * @param \Flow\Entities\Event[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Flow\Entities\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes block_id = 5;</code>
     * @return string
     */
    public function getBlockId()
    {
        return $this->block_id;
    }

    /**
     * Generated from protobuf field <code>bytes block_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockId($var)
    {
        GPBUtil::checkString($var, False);
        $this->block_id = $var;

        return $this;
    }

}

