<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/access/access.proto

namespace GPBMetadata\Flow\Access;

class Access
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Flow\Entities\Account::initOnce();
        \GPBMetadata\Flow\Entities\BlockHeader::initOnce();
        \GPBMetadata\Flow\Entities\Block::initOnce();
        \GPBMetadata\Flow\Entities\Collection::initOnce();
        \GPBMetadata\Flow\Entities\Event::initOnce();
        \GPBMetadata\Flow\Entities\Transaction::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
•"
flow/access/access.protoflow.access flow/entities/block_header.protoflow/entities/block.protoflow/entities/collection.protoflow/entities/event.protoflow/entities/transaction.protogoogle/protobuf/timestamp.proto"
PingRequest"
PingResponse"0
GetLatestBlockHeaderRequest
	is_sealed ("\'
GetBlockHeaderByIDRequest

id ("/
GetBlockHeaderByHeightRequest
height ("@
BlockHeaderResponse)
block (2.flow.entities.BlockHeader"*
GetLatestBlockRequest
	is_sealed ("!
GetBlockByIDRequest

id (")
GetBlockByHeightRequest
height ("4
BlockResponse#
block (2.flow.entities.Block"&
GetCollectionByIDRequest

id ("C
CollectionResponse-

collection (2.flow.entities.Collection"I
SendTransactionRequest/
transaction (2.flow.entities.Transaction"%
SendTransactionResponse

id ("#
GetTransactionRequest

id ("F
TransactionResponse/
transaction (2.flow.entities.Transaction"±
TransactionResultResponse0
status (2 .flow.entities.TransactionStatus
status_code (
error_message (	$
events (2.flow.entities.Event
block_id ("$
GetAccountRequest
address ("=
GetAccountResponse\'
account (2.flow.entities.Account"1
GetAccountAtLatestBlockRequest
address (":
AccountResponse\'
account (2.flow.entities.Account"G
GetAccountAtBlockHeightRequest
address (
block_height ("F
!ExecuteScriptAtLatestBlockRequest
script (
	arguments ("T
ExecuteScriptAtBlockIDRequest
block_id (
script (
	arguments ("\\
!ExecuteScriptAtBlockHeightRequest
block_height (
script (
	arguments ("&
ExecuteScriptResponse
value ("X
GetEventsForHeightRangeRequest
type (	
start_height (

end_height (">
GetEventsForBlockIDsRequest
type (	
	block_ids ("Ó
EventsResponse3
results (2".flow.access.EventsResponse.Result‹
Result
block_id (
block_height ($
events (2.flow.entities.Event3
block_timestamp (2.google.protobuf.Timestamp"
GetNetworkParametersRequest"0
GetNetworkParametersResponse
chain_id (	"\'
%GetLatestProtocolStateSnapshotRequest";
ProtocolStateSnapshotResponse
serializedSnapshot (2þ
	AccessAPI;
Ping.flow.access.PingRequest.flow.access.PingResponseb
GetLatestBlockHeader(.flow.access.GetLatestBlockHeaderRequest .flow.access.BlockHeaderResponse^
GetBlockHeaderByID&.flow.access.GetBlockHeaderByIDRequest .flow.access.BlockHeaderResponsef
GetBlockHeaderByHeight*.flow.access.GetBlockHeaderByHeightRequest .flow.access.BlockHeaderResponseP
GetLatestBlock".flow.access.GetLatestBlockRequest.flow.access.BlockResponseL
GetBlockByID .flow.access.GetBlockByIDRequest.flow.access.BlockResponseT
GetBlockByHeight$.flow.access.GetBlockByHeightRequest.flow.access.BlockResponse[
GetCollectionByID%.flow.access.GetCollectionByIDRequest.flow.access.CollectionResponse\\
SendTransaction#.flow.access.SendTransactionRequest$.flow.access.SendTransactionResponseV
GetTransaction".flow.access.GetTransactionRequest .flow.access.TransactionResponseb
GetTransactionResult".flow.access.GetTransactionRequest&.flow.access.TransactionResultResponseM

GetAccount.flow.access.GetAccountRequest.flow.access.GetAccountResponsed
GetAccountAtLatestBlock+.flow.access.GetAccountAtLatestBlockRequest.flow.access.AccountResponsed
GetAccountAtBlockHeight+.flow.access.GetAccountAtBlockHeightRequest.flow.access.AccountResponsep
ExecuteScriptAtLatestBlock..flow.access.ExecuteScriptAtLatestBlockRequest".flow.access.ExecuteScriptResponseh
ExecuteScriptAtBlockID*.flow.access.ExecuteScriptAtBlockIDRequest".flow.access.ExecuteScriptResponsep
ExecuteScriptAtBlockHeight..flow.access.ExecuteScriptAtBlockHeightRequest".flow.access.ExecuteScriptResponsec
GetEventsForHeightRange+.flow.access.GetEventsForHeightRangeRequest.flow.access.EventsResponse]
GetEventsForBlockIDs(.flow.access.GetEventsForBlockIDsRequest.flow.access.EventsResponsek
GetNetworkParameters(.flow.access.GetNetworkParametersRequest).flow.access.GetNetworkParametersResponse€
GetLatestProtocolStateSnapshot2.flow.access.GetLatestProtocolStateSnapshotRequest*.flow.access.ProtocolStateSnapshotResponseB$
org.onflow.protobuf.accessZaccessbproto3'
        , true);

        static::$is_initialized = true;
    }
}

