<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/account.proto

namespace GPBMetadata\Flow\Entities;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¡
flow/entities/account.protoflow.entities"Œ
Account
address (
balance (
code (\'
keys (2.flow.entities.AccountKey8
	contracts (2%.flow.entities.Account.ContractsEntry0
ContractsEntry
key (	
value (:8"è

AccountKey
index (

public_key (
	sign_algo (
	hash_algo (
weight (
sequence_number (
revoked (B(
org.onflow.protobuf.entitiesZentitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

