<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block.proto

namespace GPBMetadata\Flow\Entities;

class Block
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Flow\Entities\Collection::initOnce();
        \GPBMetadata\Flow\Entities\BlockSeal::initOnce();
        $pool->internalAddGeneratedFile(
            '
Š
flow/entities/block.protoflow.entitiesflow/entities/collection.protoflow/entities/block_seal.proto"ë
Block

id (
	parent_id (
height (-
	timestamp (2.google.protobuf.TimestampA
collection_guarantees (2".flow.entities.CollectionGuarantee-
block_seals (2.flow.entities.BlockSeal

signatures (B(
org.onflow.protobuf.entitiesZentitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

