<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/block_seal.proto

namespace GPBMetadata\Flow\Entities;

class BlockSeal
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
é
flow/entities/block_seal.protoflow.entities"…
	BlockSeal
block_id (
execution_receipt_id ($
execution_receipt_signatures ("
result_approval_signatures (B(
org.onflow.protobuf.entitiesZentitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

