<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/collection.proto

namespace GPBMetadata\Flow\Entities;

class Collection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ö
flow/entities/collection.protoflow.entities"1

Collection

id (
transaction_ids ("@
CollectionGuarantee
collection_id (

signatures (B(
org.onflow.protobuf.entitiesZentitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

