<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/entities/event.proto

namespace GPBMetadata\Flow\Entities;

class Event
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ì
flow/entities/event.protoflow.entities"n
Event
type (	
transaction_id (
transaction_index (
event_index (
payload (B(
org.onflow.protobuf.entitiesZentitiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

