<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow/execution/execution.proto

namespace GPBMetadata\Flow\Execution;

class Execution
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Flow\Entities\Account::initOnce();
        \GPBMetadata\Flow\Entities\Event::initOnce();
        $pool->internalAddGeneratedFile(
            '
‹
flow/execution/execution.protoflow.executionflow/entities/event.proto"
PingRequest"
PingResponse"?
GetAccountAtBlockIDRequest
block_id (
address ("F
GetAccountAtBlockIDResponse\'
account (2.flow.entities.Account"T
ExecuteScriptAtBlockIDRequest
block_id (
script (
	arguments ("/
ExecuteScriptAtBlockIDResponse
value ("¼
GetEventsForBlockIDsResponseD
results (23.flow.execution.GetEventsForBlockIDsResponse.ResultV
Result
block_id (
block_height ($
events (2.flow.entities.Event">
GetEventsForBlockIDsRequest
type (	
	block_ids ("G
GetTransactionResultRequest
block_id (
transaction_id ("p
GetTransactionResultResponse
status_code (
error_message (	$
events (2.flow.entities.Event2 
ExecutionAPIA
Ping.flow.execution.PingRequest.flow.execution.PingResponsen
GetAccountAtBlockID*.flow.execution.GetAccountAtBlockIDRequest+.flow.execution.GetAccountAtBlockIDResponsew
ExecuteScriptAtBlockID-.flow.execution.ExecuteScriptAtBlockIDRequest..flow.execution.ExecuteScriptAtBlockIDResponseq
GetEventsForBlockIDs+.flow.execution.GetEventsForBlockIDsRequest,.flow.execution.GetEventsForBlockIDsResponseq
GetTransactionResult+.flow.execution.GetTransactionResultRequest,.flow.execution.GetTransactionResultResponseB*
org.onflow.protobuf.executionZ	executionbproto3'
        , true);

        static::$is_initialized = true;
    }
}

